steps:
- name: 'gcr.io/gcp-runtimes/ubuntu_18_0_4'
  entrypoint: 'curl'
  args: ['--location',
              '${_WEBHOOK_LOCATION}',
         '--header',
              'Content-Type: application/json',
         '--data',
              '{"issues": ["${_ISSUE_KEY}"]}'
        ]