
steps:
  - id: test-builds-successfully
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    dir: gradle-example
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud builds submit --config cloudbuild.yaml
      
  - id: cleanup
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args: 
      - '-c'
      - |
        gcloud container images delete gcr.io/${PROJECT_ID}/hello-spring
      
