 - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${demo1-449207}/my-docker-repo/my-image']
     - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
        entrypoint: 'gcloud'
           args: ['compute', 'instances', 'create-with-container', 'my-vm-name', '--container-image', 'us-central1-docker.pkg.dev/${demo1-449207}/my-docker-repo/my-image']
              env:
                 - 'CLOUDSDK_COMPUTE_REGION=us-central1'
                    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
