# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
spec:
  selector:
    matchLabels:
      app: private
  replicas: 3
  template:
    metadata:
      labels:
        app: private
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: private-app-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: private
spec:
  type: LoadBalancer
  selector:
    app: private
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP